services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000 # This need to be update align with your sytem; after you run id
      - PGID=1003 # This need to be update align with your sytem; after you run id
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ./data/qbittorrent/config:/config
      - /srv/torrents:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - TZ=UTC
    volumes:
      - ./data/audiobookshelf/config:/config
      - ./data/audiobookshelf/metadata:/metadata
      # Index completed torrents directly - no promotion step needed
      - /srv/torrents/complete/audiobooks:/torrents-complete-audiobooks
    ports:
      - "13378:80"
    restart: unless-stopped
